sudo: required

language: go
go:
  - "1.10.x"

before_install:
  - cd ${TRAVIS_BUILD_DIR}/transaction && go generate
  - cd ${TRAVIS_BUILD_DIR}/state && go generate

notifications:
  slack:
    on_success: never
    on_failure: always

services:
  - docker

jobs:
  include:
  - stage: build docker images
    before_script:
    - cd ${TRAVIS_BUILD_DIR}/deploy/DOCKER
    # check builds
    script:
    - if [ "$TRAVIS_BRANCH" == "master" ]; then 
          make build;
      elif [ "$TRAVIS_BRANCH" == "develop" ]; then
          make build_develop;
      fi
  - stage: deploy docker to hub
    before_script:
    - cd ${TRAVIS_BUILD_DIR}/deploy/DOCKER
    # deploy release to docker hub
    script:
    - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_TAG" != "" ]; then 
          make login build push;
      elif [ "$TRAVIS_BRANCH" == "develop" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
          make login build_develop push_develop;
      fi

