sudo: required

#language: go
#go:
#  - tip

services:
  - docker

jobs:
  include:
  - stage: build docker images
    before_script:
    - cd ${TRAVIS_BUILD_DIR}/deploy/DOCKER
    script:
    - make login build build build_develop push push_develop

notifications:
  slack:
    on_success: never
    on_failure: always