sudo: required

language: go
go:
  - "1.10.x"

install: true

before_install:
  - go get github.com/tinylib/msgp
  - cd ${TRAVIS_BUILD_DIR}/transaction && go generate
  - cd ${TRAVIS_BUILD_DIR}/state && go generate

notifications:
  email:
    on_success: never
    on_failure: always

services:
  - docker

jobs:
  include:
  - stage: build
    before_script:
    - cd ${TRAVIS_BUILD_DIR}/deploy/DOCKER
    # check builds
    script:
    - if [ "$TRAVIS_BRANCH" == "master" ] || [ "$TRAVIS_BRANCH" == "$TRAVIS_TAG" ]; then 
          make build;
      elif [ "$TRAVIS_BRANCH" == "develop" ]; then
          make build_develop;
      fi
  - stage: run
    before_script:
    - cd ${TRAVIS_BUILD_DIR}/deploy/DOCKER
    script:
    - if [ "$TRAVIS_BRANCH" == "master" ] || [ "$TRAVIS_BRANCH" == "$TRAVIS_TAG" ]; then
          sh deploy.sh --type=node --node_ip=127.0.0.1;
      elif [ "$TRAVIS_BRANCH" == "develop" ]; then
          sh deploy.sh --type=node-dev --node_ip=127.0.0.1;
      fi
  - stage: test
    before_script:
    - cd ${TRAVIS_BUILD_DIR}
    script:
    - cd api/tests
    - go test -v handler_test.go -args -host=127.0.0.1 -update=true

          
  - stage: deploy to dockerhub
    before_script:
    - cd ${TRAVIS_BUILD_DIR}/deploy/DOCKER
    script:
    - if [ "$TRAVIS_BRANCH" == "$TRAVIS_TAG" ]; then 
          make login push;
      elif [ "$TRAVIS_BRANCH" == "develop" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
          make login push_develop;
      fi

