#
# Copyright (C) 2018 eeonevision
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#

version: "3.5"

services:

  anychaindb-mongodb-develop:
    image: mongo:latest
    container_name: anychaindb-mongodb-develop
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"
    networks:
      back:
        ipv4_address: 172.16.238.02
    expose:
      - 27017
    volumes:
      - type: bind
        source: ${DATA_ROOT}/mongo
        target: /data/db
    entrypoint: mongod --bind_ip_all --quiet

  anychaindb-abci-develop:
    image: anychaindb/abci:develop
    container_name: anychaindb-abci-develop
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"
    networks:
      back:
        ipv4_address: 172.16.238.03
    expose:
      - 26658
    depends_on:
      - anychaindb-mongodb-develop
    entrypoint: tmlc-abci --dbhost=mongodb://172.16.238.02:27017 --addr=tcp://172.16.238.03:26658 --loglevel=*:error
    
  anychaindb-node-develop:
    image: anychaindb/node:develop
    container_name: anychaindb-node-develop
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"
    networks:
      back:
        ipv4_address: 172.16.238.04
    expose:
      - 26656
      - 26657
    port:
      - 26656:26656
      - 26657:26657
    volumes:
      - type: bind
        source: ${DATA_ROOT}
        target: /tendermint
    depends_on:
      - anychaindb-abci-develop
    entrypoint: "sh -c \"\
      tendermint init && \
      tendermint node --proxy_app=tcp://172.16.238.03:26658 --p2p.laddr=tcp://172.16.238.04:26656 --rpc.laddr=tcp://172.16.238.04:26657 ${NODE_ARGS} \
      \""

  anychaindb-rest-api-develop:
    image: anychaindb/api:develop
    container_name: anychaindb-rest-api-develop
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"
    networks:
      back:
        ipv4_address: 172.16.238.05
    expose:
      - 26659
    port:
      - 26659:26659
    depends_on:
      - anychaindb-abci-develop
    entrypoint: tmlc-api --endpoint=http://172.16.238.04:26657 --ip=172.16.238.05 --port=26659 --loglevel=*:error

networks:
  back:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24